name: controlapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.7.4+74
# versinCodguncelle
 

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  curved_navigation_bar: ^1.0.3
  motion_tab_bar: ^2.0.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.6     
  fl_chart: ^1.1.1
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  path_provider: ^2.1.3
  swipe_to: ^1.0.6
  flutter_local_notifications: ^19.5.0
  smooth_page_indicator: ^2.0.1
  easy_loading_button: ^0.4.0
  loading_btn: ^1.0.3
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  flutter_email_sender: ^8.0.0
  loading_animation_widget: ^1.2.1
  googleapis_auth: ^2.0.0
  pie_chart: ^5.4.0
  provider: ^6.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.7.0
  get_it: ^9.2.0
  http: ^1.2.2
  firebase_remote_config: ^6.1.3
  firebase_crashlytics: ^5.0.6
  firebase_analytics: ^12.1.0
  flutter_native_splash: ^2.4.2
  package_info_plus: ^9.0.0
  webview_flutter: ^4.7.0  # veya en g√ºncel 4.x

  color: ^3.0.0
  go_router: ^17.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  uuid: ^4.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^3.2.4
  json_serializable: ^6.9.0
  dart_code_metrics_presets: ^2.25.1

flutter:
  generate: true
  uses-material-design: true

  assets:

    - assets/
    - assets/splash/
    - assets/mimik/
    - assets/sound/
    - assets/flags/
    - assets/icons/
    - assets/lottie/
    - assets/social_media/
